---
apiVersion: v1
kind: Namespace
metadata:
  name: tikv
  annotations:
    argocd.argoproj.io/sync-wave: "1"

---
apiVersion: v1
kind: Namespace
metadata:
  name: tikv-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
